FROM ubuntu:20.04

RUN apt update

WORKDIR /home
RUN curl -o actions-runner-osx-x64-2.283.3.tar.gz -L https://github.com/actions/runner/releases/download/v2.283.3/actions-runner-osx-x64-2.283.3.tar.gz

RUN tar -xzf actions-runner-linux-x64-2.283.3.tar.gz

RUN ./bin/installdependencies.sh

RUN chown -R 1000 /home
ENTRYPOINT ["/bin/sh", "-c", "/home/config.sh && /home/run.sh"]
