on:
  push
jobs:
  idle:
    name: Checkouts
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull the repository
        uses: actions/checkout@v2
      -
        run: ls
      -
        run: docker build -t idle_image .
      -
        run: docker images
